# Generated by Django 3.1.1 on 2020-09-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200905_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_table',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
